---
- name : Configure Docker on test-server
  hosts : test-server
  become: true
  tasks :
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker


  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 krishna21290/insure-me:1.0
